import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import configureAmplifyClient from './amplify-cognito_config'

const inter = Inter({ subsets: ["latin"] });
import { AppWrapper } from './index'
export const metadata: Metadata = {
  title: "TalkToGPT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): React.ReactElement {
  return (
    <html lang="en" suppressHydrationWarning={true} className="dark">
      <body className={inter.className}>
        <AppWrapper>
          {children}
        </AppWrapper>
        {/* {configureAmplifyClient()} */}
      </body>
    </html>
  );
}
